### ISSUE TITLE
Incompatibility with Epartment\NovaDependencyContainer package

### ISSUE THREAD

**Issue by carloshc** [dillingham/nova-attach-many#27]
Using with `Epartment\NovaDependencyContainer` causes an error and don't return values.

```php
NovaDependencyContainer::make([

    AttachMany::make('Users', 'users', User::class)

])->dependsOn('another_field', true)
```
Error:

> Trying to get property 'resourceClass' of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'resourceClass' of non-object at /vendor/dillingham/nova-attach-many/src/Http/Controllers/AttachController.php:36)

In `AttachController.php`, `$field` returns `null`. I think it's null because the `nova-attach-many` component is created in _execution time_ by the NovaDependencyContainer component.

```php
    public function getAvailableResources($request, $relationship)
    {
        $resourceClass = $request->newResource();

        $field = $resourceClass
            ->availableFields($request)
            ->where('component', 'nova-attach-many')
            ->where('attribute', $relationship)
            ->first();
```

Any ideias of solution or workaround?

**Comment by dillingham** [comment]
Sorry I don’t use that package and never intended this field to be nested. Refer to that package for questions.

**Comment by noahlocke** [comment]
@carloshc did you ever find a workaround?

**Comment by misenhower** [comment]
I was able to find a workaround for this, based in part off of [this comment](https://github.com/epartment/nova-dependency-container/issues/112#issuecomment-667088224).

In your Nova resource class:

```php
use Epartment\NovaDependencyContainer\HasDependencies;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Route;
// ...

class SomeResource extends Resource
{
    use HasDependencies {
        doesRouteRequireChildFields as baseDoesRouteRequireChildFields;
    }

    // ...

    protected function doesRouteRequireChildFields() : bool
    {
        return Str::endsWith(Route::currentRouteAction(), [
            'AttachController@create',
            'AttachController@edit',
        ]) || $this->baseDoesRouteRequireChildFields();
    }

    // ...
}
```

Explanation: Adding the `HasDependencies` trait to your resource class fixes issues with certain field types, but we have to modify one of the functions included with that trait to make it aware of the routes used by this extension. If the route ends with this extension's route, return true, otherwise, defer to the "base" trait's `doesRouteRequireChildFields` method.

This seems to fix the issue for me.
